In [ ]:
import numpy as np
import keras
from keras import layers


def readucr(filename):
    data = np.loadtxt(filename, delimiter="\t")
    y = data[:, 0]
    x = data[:, 1:]
    return x, y.astype(int)


root_url = "https://raw.githubusercontent.com/hfawaz/cd-diagram/master/FordA/"

x_train, y_train = readucr(root_url + "FordA_TRAIN.tsv")
x_test, y_test = readucr(root_url + "FordA_TEST.tsv")

x_train = x_train.reshape((x_train.shape[0], x_train.shape[1], 1))
x_test = x_test.reshape((x_test.shape[0], x_test.shape[1], 1))

n_classes = len(np.unique(y_train))

idx = np.random.permutation(len(x_train))
x_train = x_train[idx]
y_train = y_train[idx]

y_train[y_train == -1] = 0
y_test[y_test == -1] = 0

In [ ]:
y_train[6]

1

In [ ]:
!pip install vallenae
!pip install PyWavelets

In [ ]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import vallenae as vae
from tqdm import tqdm
import numpy as np
import matplotlib.pyplot as plt
import pywt
import keras
from keras import layers

TRADB = Path("/content/fiber-friction.tradb")
tradb=vae.io.TraDatabase(TRADB)
full_df = tradb.read()
df1=pd.DataFrame()
df1['data']=full_df['data']
df1['label']=0
df1

Tra: 100%|██████████| 7011/7011 [00:00<00:00, 7648.72it/s]


data  label
trai                                                           
3      [3.0445285e-06, 3.0445285e-06, -2.13117e-05, -...      0
4      [6.089057e-06, 0.0, 3.0445285e-06, 0.0, -9.133...      0
7      [3.0445285e-06, 6.089057e-06, 0.0, 0.0, -1.217...      0
8      [-3.0445285e-06, 6.089057e-06, 0.0, 3.0445285e...      0
11     [6.089057e-06, 2.13117e-05, 3.0445284e-05, 3.6...      0
...                                                  ...    ...
24118  [-3.0445285e-06, -9.133586e-06, -1.2178114e-05...      0
24119  [9.133586e-06, 6.089057e-06, 3.0445285e-06, -3...      0
24121  [-9.133586e-06, -9.133586e-06, -9.133586e-06, ...      0
24125  [0.0, 9.133586e-06, 9.133586e-06, 6.089057e-06...      0
24126  [-1.2178114e-05, -1.5222642e-05, -1.2178114e-0...      0

[7011 rows x 2 columns]

In [ ]:
TRADB = Path("/content/sand-friction.tradb")
tradb=vae.io.TraDatabase(TRADB)
full_df = tradb.read()
df2=pd.DataFrame()
df2['data']=full_df['data']
df2['label']=1
df2

Tra: 100%|██████████| 6988/6988 [00:00<00:00, 8233.36it/s]


data  label
trai                                                           
1      [9.133586e-06, 3.0445285e-06, 9.133586e-06, 1....      1
2      [0.0, 0.0, -1.5222642e-05, -1.2178114e-05, -3....      1
3      [6.089057e-06, 0.0, -9.133586e-06, -3.0445285e...      1
10     [-6.089057e-06, -1.5222642e-05, -9.133586e-06,...      1
11     [-3.0445285e-06, 0.0, 0.0, 6.089057e-06, 0.0, ...      1
...                                                  ...    ...
13578  [-3.0445285e-06, 3.0445285e-06, 6.089057e-06, ...      1
13581  [-3.0445285e-06, -3.0445285e-06, 3.0445285e-06...      1
13582  [-1.2178114e-05, -6.089057e-06, 3.0445285e-06,...      1
13583  [3.0445285e-06, -6.089057e-06, -6.089057e-06, ...      1
13584  [-3.0445285e-06, 6.089057e-06, 3.0445285e-06, ...      1

[6988 rows x 2 columns]

In [ ]:
TRADB = Path("/content/sand.tradb")
tradb=vae.io.TraDatabase(TRADB)
full_df = tradb.read()
df3=pd.DataFrame()
df3['data']=full_df['data']
df3['label']=2
df3

Tra: 100%|██████████| 6929/6929 [00:02<00:00, 2604.48it/s]


data  label
trai                                                           
5      [-3.0445285e-06, 0.0, -3.0445285e-06, -9.13358...      2
8      [-2.7400756e-05, -2.4356228e-05, -2.13117e-05,...      2
13     [1.2178114e-05, 1.2178114e-05, 1.2178114e-05, ...      2
16     [4.26234e-05, 3.3489814e-05, 3.0445284e-05, 2....      2
21     [-1.5222642e-05, -1.5222642e-05, 0.0, -3.04452...      2
...                                                  ...    ...
40384  [0.0, -3.0445285e-06, -3.0445285e-06, 3.044528...      2
40388  [0.0, 1.2178114e-05, 0.0, 3.0445285e-06, 3.044...      2
40399  [1.2178114e-05, 0.0, 3.0445285e-06, 3.0445285e...      2
40402  [1.5222642e-05, 9.133586e-06, 1.5222642e-05, 9...      2
40406  [-3.0445285e-06, -2.13117e-05, -3.0445285e-06,...      2

[6929 rows x 2 columns]

In [ ]:
TRADB = Path("/content/sherbet-powder.tradb")
tradb=vae.io.TraDatabase(TRADB)
full_df = tradb.read()
df4=pd.DataFrame()
df4['data']=full_df['data']
df4['label']=3
df4

Tra: 100%|██████████| 6929/6929 [00:01<00:00, 4814.58it/s]


data  label
trai                                                           
3      [-3.0445285e-06, -6.089057e-06, 0.0, -1.217811...      3
11     [6.089057e-06, 3.0445285e-06, 6.089057e-06, 9....      3
16     [6.089057e-06, 0.0, 6.089057e-06, 0.0, 6.08905...      3
18     [-1.5222642e-05, -2.13117e-05, -1.2178114e-05,...      3
23     [-9.133586e-06, -9.133586e-06, -1.2178114e-05,...      3
...                                                  ...    ...
31196  [-6.089057e-06, -3.0445285e-06, 0.0, -3.044528...      3
31197  [-3.0445285e-06, 0.0, 0.0, 3.0445285e-06, -3.0...      3
31198  [-6.089057e-06, -6.089057e-06, -1.2178114e-05,...      3
31204  [-3.0445285e-06, 6.089057e-06, 0.0, 6.089057e-...      3
31206  [3.0445285e-06, 3.0445285e-06, 6.089057e-06, 9...      3

[6929 rows x 2 columns]

In [ ]:
result = pd.concat([df1, df2,df3,df4], ignore_index=True)
result

data  label
0      [3.0445285e-06, 3.0445285e-06, -2.13117e-05, -...      0
1      [6.089057e-06, 0.0, 3.0445285e-06, 0.0, -9.133...      0
2      [3.0445285e-06, 6.089057e-06, 0.0, 0.0, -1.217...      0
3      [-3.0445285e-06, 6.089057e-06, 0.0, 3.0445285e...      0
4      [6.089057e-06, 2.13117e-05, 3.0445284e-05, 3.6...      0
...                                                  ...    ...
27852  [-6.089057e-06, -3.0445285e-06, 0.0, -3.044528...      3
27853  [-3.0445285e-06, 0.0, 0.0, 3.0445285e-06, -3.0...      3
27854  [-6.089057e-06, -6.089057e-06, -1.2178114e-05,...      3
27855  [-3.0445285e-06, 6.089057e-06, 0.0, 6.089057e-...      3
27856  [3.0445285e-06, 3.0445285e-06, 6.089057e-06, 9...      3

[27857 rows x 2 columns]

In [ ]:
a=result.drop(columns=['label'])
c=a["data"].tolist()
c

[array([ 3.0445285e-06,  3.0445285e-06, -2.1311700e-05, ...,
         5.1756986e-05,  4.8712456e-05,  4.8712456e-05], dtype=float32),
 array([ 6.0890570e-06,  0.0000000e+00,  3.0445285e-06, ...,
        -2.1311700e-05, -1.5222642e-05,  0.0000000e+00], dtype=float32),
 array([ 3.0445285e-06,  6.0890570e-06,  0.0000000e+00, ...,
        -2.7400756e-05, -1.2178114e-05, -1.2178114e-05], dtype=float32),
 array([-3.0445285e-06,  6.0890570e-06,  0.0000000e+00, ...,
         7.0024158e-05,  7.0024158e-05,  5.4801512e-05], dtype=float32),
 array([6.0890570e-06, 2.1311700e-05, 3.0445284e-05, ..., 3.0445285e-06,
        2.1311700e-05, 3.3489814e-05], dtype=float32),
 array([-6.0890570e-06, -3.0445285e-06,  0.0000000e+00, ...,
         2.4356228e-05,  1.8267172e-05,  2.4356228e-05], dtype=float32),
 array([6.0890570e-06, 0.0000000e+00, 3.0445285e-06, ..., 3.3489814e-05,
        4.2623400e-05, 5.1756986e-05], dtype=float32),
 array([ 3.0445284e-05,  3.0445284e-05,  1.8267172e-05, ...,
        -3.04

In [ ]:
k=[]
for i in range(len(c)) :

    l=c[i].tolist()
    k.append(l)
k

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
d= pad_sequences(k, padding='post',value=0,dtype='float32',maxlen=5000)
d


In [ ]:
y=np.array(result['label'].values)
y

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(d, y, test_size=0.2, random_state=42)
x_train = np.expand_dims(x_train, axis=-1)
x_train.shape

In [ ]:
x_test = np.expand_dims(x_test, axis=-1)
x_test.shape

In [ ]:
n_classes = len(np.unique(y_train))

In [ ]:
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    # Attention and Normalization
    x = layers.MultiHeadAttention(
        key_dim=head_size, num_heads=num_heads, dropout=dropout
    )(inputs, inputs)
    x = layers.Dropout(dropout)(x)
    x = layers.LayerNormalization(epsilon=1e-6)(x)
    res = x + inputs

    # Feed Forward Part
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu")(res)
    x = layers.Dropout(dropout)(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    x = layers.LayerNormalization(epsilon=1e-6)(x)
    return x + res

In [ ]:
def build_model(
    input_shape,
    head_size,
    num_heads,
    ff_dim,
    num_transformer_blocks,
    mlp_units,
    dropout=0,
    mlp_dropout=0,
):
    inputs = keras.Input(shape=input_shape)
    x = inputs
    for _ in range(num_transformer_blocks):
        x = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)

    x = layers.GlobalAveragePooling1D(data_format="channels_last")(x)
    for dim in mlp_units:
        x = layers.Dense(dim, activation="relu")(x)
        x = layers.Dropout(mlp_dropout)(x)
    outputs = layers.Dense(n_classes, activation="softmax")(x)
    return keras.Model(inputs, outputs)

In [ ]:
input_shape = x_train.shape[1:]

model = build_model(
    input_shape,
    head_size=256,
    num_heads=4,
    ff_dim=4,
    num_transformer_blocks=4,
    mlp_units=[128],
    mlp_dropout=0.4,
    dropout=0.25,
)

model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    metrics=["sparse_categorical_accuracy"],
)
model.summary()

callbacks = [keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)]

model.fit(
    x_train,
    y_train,
    validation_split=0.2,
    epochs=150,
    batch_size=64,
    callbacks=callbacks,
)

model.evaluate(x_test, y_test, verbose=1)